### ISSUE TITLE
Logo Ideas!

### ISSUE THREAD

**Issue by daniellecrobinson** [BioData-Club/BioData-Club.github.io#1]

**Comment by erictleung** [comment]
We can probably use this (http://www.flaticon.com/packs/data-analytics) to find some nice icon for our logo. 

In terms of color schemes, we can use http://paletton.com, http://www.colourlovers.com/palettes, or http://colorbrewer2.org to find a color scheme, if necessary.

There's also someone's suggestion to make a hexagon sticker. We can take a look at [hexbin](http://hexb.in/) for some ideas (GitHub: https://github.com/maxogden/hexbin).

**Comment by lwinfree** [comment]
+1
