### ISSUE TITLE
09-29-2017 Good Enough Practices in Scientific Computing

### ISSUE THREAD

**Issue by daniellecrobinson** [BioData-Club/BioData-Club.github.io#18]
:tada: Welcome to the 2017-2018 academic year! :tada:

BioData Club will kick off the new year with a discussion of Wilson et al.'s 2017 work [Good Enough Practices in Scientific Computing](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005510)

OHSU BICC 124, 29 September 2017, 04:00 PM 

**Add your favorite quotes, questions for Greg, and ideas of skills you want to learn to this issue**

What is good enough? What are the skills and tools every researcher should know? Wilson et al. recommend "a minimum set of tools and techniques that we believe every researcher can and should consider adopting" - read the paper to learn what their recommendations are and then let's discuss barriers to adoption and how BioData Club can support you as you learn. We are excited to starting the year off right by considering project and data management skills to make your life in the lab easier!

We'll also introduce the group, talk about what we are working on for the 2017-2018 year, and invite **you** to join our steering committee or teach a session!

**Comment by daniellecrobinson** [comment]
As always, this BioData Club session is open to all!

**Comment by daniellecrobinson** [comment]
Questions and discussion points below:

```Be ruthless about eliminating duplication (2c). Write and reuse functions instead of copying and pasting code, and use data structures like lists instead of creating many closely related variables, " How many of you regularly write functions? Why is it hard to do?```


Raise your hand if you've done this (no shame, Danielle has): 
``` Do not comment and uncomment sections of code to control a program's behavior (2h), since this is error prone and makes it difficult or impossible to automate analyses. Instead, put if/else statements in the program to control what it does.```

Raise your hand if you've done this: 
```Decide on communication strategies (3c). Make explicit decisions about (and publicize where appropriate) how members of the project will communicate with each other and with externals users/collaborators. This includes the location and technology for email lists, chat channels, voice/video conferencing, documentation, and meeting notes, as well as which of these channels will be public or private.```

Let's talk about why this is hard.

Improving your workflow saves time!
```Data are cheap, time is expensive```

**Comment by daniellecrobinson** [comment]
Etherpad! https://public.etherpad-mozilla.org/p/biodataClub-goodenough

**Comment by laderast** [comment]
Great! I will add it to the reminder email.
