### ISSUE TITLE
Change banner image on website

### ISSUE THREAD

**Issue by erictleung** [BioData-Club/BioData-Club.github.io#2]
As per discussion, the default banner image of coffee and hands on a laptop should be changed to something else. 

The current image in the repository is [here](https://github.com/BioData-Club/BioData-Club.github.io/blob/master/img/header1.jpg) and then line of code that needs to be changed is [here](https://github.com/BioData-Club/BioData-Club.github.io/blob/685e60aa1b0eb6aabce77e74918a99c64f03ba17/_includes/css/agency.css#L288)

We could use some aerial image of OHSU like this one.

![](http://mba-healthcare-management.com/wp-content/uploads/2014/08/Oregon-Health-Science-University-masters-in-healthcare-information-management-e1410959119247.jpg)

Or we could use a more "bioinformatics" images like this one.

![](http://dhmri.org/assets/PageImage-Bioinformatics.jpg)

**Comment by rchampieux** [comment]
+1 to this.  I like the bioinformatics image.  It’s striking, but not too specific.

**Comment by erictleung** [comment]
Resolved with https://github.com/BioData-Club/BioData-Club.github.io/commit/a9ea94081b552667de346d46121bdbcdab603416.
