### ISSUE TITLE
List of Past Workshops

### ISSUE THREAD

**Issue by laderast** [BioData-Club/BioData-Club.github.io#4]
Here is a list of past workshops. Some of them are just PPTs so we would need to archive them somewhere. 

# Documenting and Typesetting

+ [The Magic of Markdown](https://github.com/laderast/magic-of-markdown) - An introduction to the many uses of Markdown, including RMarkdown for reproducible scripting.
+ [Intro to LaTeX](https://www.sharelatex.com/project/557bf6fa3a7173c33460c7e8) - Eric Leung's sharelatex document showing lots of features in LaTeX.

# R Related

+ [Intro To Data Carpentry](https://github.com/erictleung/tutorial-tidyverse) - The Tidyverse tutorial
+ [ggplot2 Tutorial](https://github.com/laderast/ggplot2-intro) - A gentle introduction to ggplot2 and the grammar of graphics.
+ [ggvis Tutorial](https://github.com/laderast/ggvis-intro) - A gentle introduction to ggvis, which adds extra interactivity to Shiny plots using the magic of vega.
+ [Shiny Tutorial](https://github.com/laderast/shinyTutorial) - A do it yourself tutorial to try out Shiny, ggplot2, and dplyr for interactive graphics.
+ [Dplyr Tutorial](https://github.com/justmarkham/dplyr-tutorial) - Nathan gave a version of this.
+ [GRanges Tutorial]() - Nathan gave a version of this talking about the GRanges package for managing genomics data.

# Unix Related

+ [Exacloud Tutorial](https://www.dropbox.com/s/chg6ciknxonp5el/exacloud-tutorial.pdf) - A DIY tutorial to running jobs on Exacloud, OHSU's cluster computing environment.
+ [Bootstrapping Software](https://github.com/greenstick/bootstrapping-package-management-on-exacloud) - Ben Cordier's tutorial on bootstrapping installing software when you don't have root access
+ [Stupid Unix Tricks](https://gist.github.com/laderast/119eff812ce76081ba5e941f1054f3a1) - Some hints for working on the command lines
+ [Tips for working with R on exacloud]() - Adam Therneau gave a talk on how he manages software on exacloud
+ [Vim Tutorial]() - Eric Leung's tutorial for learning the vim editor

# Software Development Related

+ [Advanced Git Tutorial](https://github.com/ericearl/fancy_git) - Eric Earl's advanced git workshop
+ [TensorFlow Tutorial](https://github.com/ryanmswan/tensorflow_mnist/) - Ryan Swan's TensorFlow Tutorial
+ [NoSQL Databases]()
+ [Graph Database Tutorial](https://github.com/greenstick/neo4j-tutorial)
+ [Unit Testing](https://github.com/keeppythonweird/catinabox) - Alex and Rory gave a talk about integrating git with unit testing frameworks
+ + [Unit Testing in R]() - Nathan gave a talk on using testthat() for unit testing of his package.

# Other useful stuff for grad school (not by us)

+ [Statistics For Biologists](http://www.nature.com/collections/qghhqm)
+ [How to be a Modern Scientist](https://leanpub.com/modernscientist)
+ [PhD Starter Kit](https://raoofphysics.github.io/phd-starter-kit/)
+ [What can Data Scientists Learn From DevOps?](http://redmonk.com/dberkholz/2012/11/06/what-can-data-scientists-learn-from-devops/)

**Comment by rchampieux** [comment]
Jeff Leek, author of How to Be a Modern Scientist, is going to be on campus in mid May.  I had hoped he might be available to participate in a Data Jamboree, but he can't stay through Friday.  But maybe he could do an hour BioData Club workshop on Thursday....if you all think that would be useful.
