### ISSUE TITLE
Link from BioData Club page to repo is broken

### ISSUE THREAD

**Issue by WatanabeSmith** [BioData-Club/BioData-Club.github.io#8]
On left hand side of page:
WANT TO BE NOTIFIED OF OUR UPCOMING EVENTS?
Head over to GitHub and watch our repository, like this:

The link points to: https://github.com/BioData-Club/BioData-Club
Should point to: https://github.com/BioData-Club/BioData-Club.github.io

**Comment by erictleung** [comment]
@WatanabeSmith thanks for letting us know! I've added the changes and will hopefully fix it.
